apiVersion: apps/v1
kind: Deployment
metadata:
  name: blog
  labels:
    app: blog
spec:
  replicas: 1
  selector:
    matchLabels:
      app: blog
  template:
    metadata:
      labels:
        app: blog
    spec:
      containers:
        - name: blog
          image: ghost:4.22.1
          imagePullPolicy: Always
          volumeMounts:
            - mountPath: /var/lib/ghost/content
              name: content
          volumes:
            - name: content
              persistentVolumeClaim:
                claimName: blog-content
          ports:
            - containerPort: 2368
          env:
            - name: url
              value: http://portosanti.com
---
apiVersion: v1
kind: Service
metadata:
  name: blog
spec:
  type: LoadBalancer
  selector:
    app: blog
  ports:
    - protocol: TCP
      port: 80
      targetPort: 2368
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: blog-content
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
  storageClassName: do-block-storage
