apiVersion: apps/v1
kind: Deployment
metadata:
  name: blog
  labels:
    app: blog
spec:
  replicas: 1
  selector:
    matchLabels:
      app: blog
  template:
    metadata:
      labels:
        app: blog
    spec:
      containers:
        - name: blog
          image: ghost:4.22.1
          imagePullPolicy: Always
          ports:
            - containerPort: 2368
          env:
            - name: url
              value: http://portosanti.com
